version: '3'
services:
  store:
    build:
      context: ./
    image: 'ancolin/store:latest'
    ports:
      - '5000:80'
    depends_on:
      - redis
  redis:
    image: 'redis:latest'
    volumes:
      - './redis_data:/data'
